# 错误处理

在排查问题的时候想查证 `During handling of the above exception, another exception occurred:
`是什么意思，然后找到了个不错的[博客](https://mozillazg.com/2016/08/python-the-right-way-to-catch-exception-then-reraise-another-exception.html)，讲捕获异常再抛出另一个异常的正确处理方式